webtalk_init -webtalk_dir /home/veeyceey/Documents/workspace/github/AUKV-2/AUK-V/vivado/AUK-V/AUK-V.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-10-27 12:05:03" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211651066_0_0_103" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "43sstqvtumaqi2vd8gb2r3avu2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3900.449 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.624 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1603775145000" -context "sdk\\\\bsp/1603775145000"
webtalk_add_data -client sdk -key hwid -value "1603774995000" -context "sdk\\\\bsp/1603775145000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1603775145000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1603775145000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1603775145000"
webtalk_add_data -client sdk -key uid -value "1603775146000" -context "sdk\\\\application/1603775146000"
webtalk_add_data -client sdk -key hwid -value "1603774995000" -context "sdk\\\\application/1603775146000"
webtalk_add_data -client sdk -key bspid -value "1603775145000" -context "sdk\\\\application/1603775146000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1603775146000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1603775146000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1603775146000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1603775146000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1603775146000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1603775146000"
webtalk_add_data -client sdk -key projSize -value "195.09765625" -context "sdk\\\\application/1603775146000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1603780503855"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1603780503855"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1603780503855"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1603780503855"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1603780503855"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1603780503855"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1603780503855"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1603780503855"
webtalk_transmit -clientid 4001739468 -regid "211651066_0_0_103" -xml /home/veeyceey/Documents/workspace/github/AUKV-2/AUK-V/vivado/AUK-V/AUK-V.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/veeyceey/Documents/workspace/github/AUKV-2/AUK-V/vivado/AUK-V/AUK-V.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/veeyceey/Documents/workspace/github/AUKV-2/AUK-V/vivado/AUK-V/AUK-V.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
