# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_ila_0_0/example_led_ila_0_0.xci
# IP: The module: 'example_led_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_led_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_led_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_ila_0_0/example_led_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_led_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_ila_0_0/example_led_ila_0_0.xci
# IP: The module: 'example_led_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_led_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_led_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_ila_0_0/example_led_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_led_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
