set_property SRC_FILE_INFO {cfile:/home/veeyceey/Documents/workspace/github/AUK-V/boards/zturn/system.xdc rfile:../../../../../boards/zturn/system.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports {LEDS[0]}]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports {LEDS[1]}]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports {LEDS[2]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list example_led_i/clk_wiz_0/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[0]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[1]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[2]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[3]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[4]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[5]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[6]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[7]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[8]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[9]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[10]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[11]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[12]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[13]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[14]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[15]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[16]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[17]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[18]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[19]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[20]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[21]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[22]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[23]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[24]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[25]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[26]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[27]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[28]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[29]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[30]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/o_wb_data[31]}]]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[0]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[1]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[2]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[3]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[4]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[5]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[6]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[7]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[8]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[9]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[10]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[11]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[12]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[13]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[14]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[15]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[16]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[17]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[18]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[19]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[20]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[21]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[22]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[23]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[24]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[25]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[26]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[27]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[28]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[29]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[30]} {example_led_i/sciv_example_system_0/U0/SC0/SC0/fe0_pc[31]}]]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
