#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Sep 04 08:16:45 IST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_sciv_core_behav -key {Behavioral:sim_1:Functional:tb_sciv_core} -tclbatch tb_sciv_core.tcl -protoinst "protoinst_files/example_led.protoinst" -view /home/veeyceey/Documents/workspace/github/AUK-V/vivado/SCiV/decode.wcfg -view /home/veeyceey/Documents/workspace/github/AUK-V/vivado/SCiV/tb_sciv_core_behav3.wcfg -view /home/veeyceey/Documents/workspace/github/AUK-V/vivado/SCiV/mem.wcfg -log simulate.log"
xsim tb_sciv_core_behav -key {Behavioral:sim_1:Functional:tb_sciv_core} -tclbatch tb_sciv_core.tcl -protoinst "protoinst_files/example_led.protoinst" -view /home/veeyceey/Documents/workspace/github/AUK-V/vivado/SCiV/decode.wcfg -view /home/veeyceey/Documents/workspace/github/AUK-V/vivado/SCiV/tb_sciv_core_behav3.wcfg -view /home/veeyceey/Documents/workspace/github/AUK-V/vivado/SCiV/mem.wcfg -log simulate.log

