#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Sep 15 22:59:57 IST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_aukv_example_native_behav -key {Behavioral:sim_1:Functional:tb_aukv_example_native} -tclbatch tb_aukv_example_native.tcl -view /home/veeyceey/Documents/workspace/temp/AUK-V/vivado/AUK-V/tb_sciv_core_behav.wcfg -log simulate.log"
xsim tb_aukv_example_native_behav -key {Behavioral:sim_1:Functional:tb_aukv_example_native} -tclbatch tb_aukv_example_native.tcl -view /home/veeyceey/Documents/workspace/temp/AUK-V/vivado/AUK-V/tb_sciv_core_behav.wcfg -log simulate.log

