#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jun 03 19:45:03 IST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_sciv_core_behav -key {Behavioral:sim_1:Functional:tb_sciv_core} -tclbatch tb_sciv_core.tcl -view /home/veeyceey/Documents/workspace/github/SCiV/vivado/SCiV/decode.wcfg -view /home/veeyceey/Documents/workspace/github/SCiV/vivado/SCiV/tb_sciv_core_behav.wcfg -view /home/veeyceey/Documents/workspace/github/SCiV/vivado/SCiV/tb_sciv_core_behav2.wcfg -view /home/veeyceey/Documents/workspace/github/SCiV/vivado/SCiV/tb_sciv_core_behav4.wcfg -log simulate.log"
xsim tb_sciv_core_behav -key {Behavioral:sim_1:Functional:tb_sciv_core} -tclbatch tb_sciv_core.tcl -view /home/veeyceey/Documents/workspace/github/SCiV/vivado/SCiV/decode.wcfg -view /home/veeyceey/Documents/workspace/github/SCiV/vivado/SCiV/tb_sciv_core_behav.wcfg -view /home/veeyceey/Documents/workspace/github/SCiV/vivado/SCiV/tb_sciv_core_behav2.wcfg -view /home/veeyceey/Documents/workspace/github/SCiV/vivado/SCiV/tb_sciv_core_behav4.wcfg -log simulate.log

