# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/boards/zturn/system.xdc

# Block Designs: bd/example_led/example_led.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==example_led || ORIG_REF_NAME==example_led} -quiet] -quiet

# IP: bd/example_led/ip/example_led_processing_system7_0_0/example_led_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==example_led_processing_system7_0_0 || ORIG_REF_NAME==example_led_processing_system7_0_0} -quiet] -quiet

# IP: bd/example_led/ip/example_led_sciv_example_system_0_0/example_led_sciv_example_system_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==example_led_sciv_example_system_0_0 || ORIG_REF_NAME==example_led_sciv_example_system_0_0} -quiet] -quiet

# IP: bd/example_led/ip/example_led_ila_0_0/example_led_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==example_led_ila_0_0 || ORIG_REF_NAME==example_led_ila_0_0} -quiet] -quiet

# IP: bd/example_led/ip/example_led_xlconstant_0_0/example_led_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==example_led_xlconstant_0_0 || ORIG_REF_NAME==example_led_xlconstant_0_0} -quiet] -quiet

# IP: bd/example_led/ip/example_led_util_vector_logic_0_0/example_led_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==example_led_util_vector_logic_0_0 || ORIG_REF_NAME==example_led_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/example_led/ip/example_led_clk_wiz_0_1/example_led_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==example_led_clk_wiz_0_1 || ORIG_REF_NAME==example_led_clk_wiz_0_1} -quiet] -quiet

# IP: bd/example_led/ip/example_led_vio_0_0/example_led_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==example_led_vio_0_0 || ORIG_REF_NAME==example_led_vio_0_0} -quiet] -quiet

# XDC: bd/example_led/example_led_ooc.xdc
