# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_clk_wiz_0_1/example_led_clk_wiz_0_1.xci
# IP: The module: 'example_led_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_clk_wiz_0_1/example_led_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_led_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_clk_wiz_0_1/example_led_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_led_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_clk_wiz_0_1/example_led_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_led_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_clk_wiz_0_1/example_led_clk_wiz_0_1.xci
# IP: The module: 'example_led_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_clk_wiz_0_1/example_led_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_led_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_clk_wiz_0_1/example_led_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_led_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.srcs/sources_1/bd/example_led/ip/example_led_clk_wiz_0_1/example_led_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'example_led_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
