webtalk_init -webtalk_dir /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.sim/sim_1/behav/xsim/xsim.dir/tb_aukv_example_native_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Sep 18 22:36:20 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "891d9871-5180-4ee7-a475-72b2a6ee5a04" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c84a59af210a4fd884dd97f83e7f28a4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2200.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "500100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.89_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "123868_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2584183011 -regid "" -xml /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.sim/sim_1/behav/xsim/xsim.dir/tb_aukv_example_native_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.sim/sim_1/behav/xsim/xsim.dir/tb_aukv_example_native_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/veeyceey/Documents/workspace/github/AUK-V/vivado/AUK-V/AUK-V.sim/sim_1/behav/xsim/xsim.dir/tb_aukv_example_native_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
