set_property SRC_FILE_INFO {cfile:/home/veeyceey/Documents/workspace/github/AUK-V/boards/zturn/system.xdc rfile:../../../../../boards/zturn/system.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports {LEDS[0]}]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports {LEDS[1]}]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports {LEDS[2]}]
